CREATE TABLE TRADE
(
    ID                  IDENTITY                     NOT NULL,
    STATUS              VARCHAR(20)                  NOT NULL,
    AMOUNT              NUMERIC(12, 2) DEFAULT 0     NOT NULL,
    RELEASED_DATE_TIME  TIMESTAMP,
    RELEASE_DATE_TIME   TIMESTAMP,
    CUTOFF_DATE_TIME    TIMESTAMP                    NOT NULL,
    CREATED_DATE_TIME   TIMESTAMP      DEFAULT NOW() NOT NULL,
    CONSTRAINT TRADE_PK PRIMARY KEY (ID)
);

CREATE TABLE INT_LOCK
(
    LOCK_KEY     CHAR(36)     NOT NULL,
    REGION       VARCHAR(100) NOT NULL,
    CLIENT_ID    CHAR(36),
    CREATED_DATE TIMESTAMP    NOT NULL,
    CONSTRAINT INT_LOCK_PK PRIMARY KEY (LOCK_KEY, REGION)
);
